# Generated by Django 5.2.5 on 2026-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('pillar', models.CharField(blank=True, max_length=200)),
                ('office', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('duration', models.CharField(blank=True, choices=[('', 'Single Day'), ('2 days', '2 Days'), ('3 days', '3 Days'), ('4 days', '4 Days'), ('5 days', '5 Days'), ('1 week', '1 Week'), ('2 weeks', '2 Weeks'), ('1 month', '1 Month')], max_length=50)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Moved', 'Moved')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('1. Food Security', '1. Food Security'), ('2. Water Sufficiency', '2. Water Sufficiency'), ('3. Ecological and Environmental stability', '3. Ecological and Environmental stability'), ('4. Human Security', '4. Human Security'), ('5. Climate-Smart Industries and Services', '5. Climate-Smart Industries and Services'), ('6. Sustainable Energy', '6. Sustainable Energy'), ('7. Knowledge and Capacity Development', '7. Knowledge and Capacity Development')], max_length=100)),
                ('office', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=500)),
                ('accomplishment', models.IntegerField(default=0, help_text='Accomplishment percentage (0-100)')),
                ('target', models.CharField(blank=True, max_length=500, null=True)),
                ('actual', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Pending', 'Pending')], default='In Progress', max_length=20)),
                ('quarter', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
