# Generated by Django 6.0.2 on 2026-03-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('pillar', models.CharField(blank=True, max_length=200)),
                ('office', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('duration', models.CharField(blank=True, choices=[('', 'Single Day'), ('2 days', '2 Days'), ('3 days', '3 Days'), ('4 days', '4 Days'), ('5 days', '5 Days'), ('1 week', '1 Week'), ('2 weeks', '2 Weeks'), ('1 month', '1 Month')], max_length=50)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
